import json
import os
import datetime

catalog_path = "docs/knowledge/source-catalog.json"

with open(catalog_path, "r") as f:
    catalog = json.load(f)

new_docs = [
    {
        "source_id": "DOC-NHS-004",
        "title": "Asthma",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Asthma",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "publication_date": "UNKNOWN",
        "last_updated_date": "UNKNOWN",
        "version": "Current",
        "canonical_url": "https://www.nhs.uk/conditions/asthma/",
        "final_verified_url": "https://www.nhs.uk/conditions/asthma/",
        "access_method": "Public URL",
        "usage_licensing_status": "NHS Copyright",
        "currentness_status": "Current authoritative version",
        "scope": "Symptoms, causes, and management of Asthma",
        "why_relevant": "Provides high-value chronic condition intent",
        "contains_consumer_health_info": True,
        "contains_clinical_management_guidance": False,
        "is_bangladesh_specific": False,
        "duplicate_conflict_status": "No conflicts",
        "review_date": datetime.datetime.now().strftime("%Y-%m-%d"),
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "licence_version": "3.0",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "translation_status": "PERMITTED (must not claim official NHS endorsement)",
        "third_party_content_status": "No embedded 3rd party content found; standard NHS logos excluded from OGL.",
        "redirect_notes": "No redirects.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "superseded_by": "None",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0, which explicitly permits copying, publishing, and transformation.",
        "reviewer_date": datetime.datetime.now().strftime("%Y-%m-%d")
    },
    {
        "source_id": "DOC-NHS-005",
        "title": "Burns and scalds",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Burns and scalds",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/burns-and-scalds/",
        "final_verified_url": "https://www.nhs.uk/conditions/burns-and-scalds/",
        "scope": "First aid for burns and scalds",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "No redirects.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-006",
        "title": "Cuts and grazes",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Cuts and grazes",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/cuts-and-grazes/",
        "final_verified_url": "https://www.nhs.uk/conditions/cuts-and-grazes/",
        "scope": "First aid for cuts and grazes",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Contains outbound links to St John Ambulance; textual content itself is NHS OGL.",
        "redirect_notes": "No redirects.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-007",
        "title": "Dehydration",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Dehydration",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/dehydration/",
        "final_verified_url": "https://www.nhs.uk/conditions/dehydration/",
        "scope": "Symptoms and treatment of dehydration",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "No redirects.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-008",
        "title": "Diarrhoea and vomiting",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Diarrhoea and vomiting",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/diarrhoea-and-vomiting/",
        "final_verified_url": "https://www.nhs.uk/symptoms/diarrhoea-and-vomiting/",
        "scope": "Symptoms, home treatment, and urgency for diarrhoea and vomiting",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "Internal redirect to /symptoms/diarrhoea-and-vomiting/. Target is still NHS infrastructure.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-009",
        "title": "Headaches",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Headaches",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/headaches/",
        "final_verified_url": "https://www.nhs.uk/symptoms/headaches/",
        "scope": "Common causes of headaches and when to seek help",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "Internal redirect to /symptoms/headaches/.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-010",
        "title": "High temperature (fever) in children",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Child fever",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/fever-in-children/",
        "final_verified_url": "https://www.nhs.uk/symptoms/fever-in-children/",
        "scope": "Pediatric fever symptoms and management",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "Internal redirect to /symptoms/fever-in-children/.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-011",
        "title": "Anaphylaxis",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Anaphylaxis",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/anaphylaxis/",
        "final_verified_url": "https://www.nhs.uk/conditions/anaphylaxis/",
        "scope": "Severe allergic reaction symptoms and immediate emergency response",
        "approval_status": "APPROVED_FOR_PRODUCTION_REUSE",
        "rights_status": "Open Government Licence v3.0",
        "licence_name": "Open Government Licence v3.0 & NHS Terms",
        "commercial_use_status": "PERMITTED",
        "adaptation_status": "PERMITTED",
        "third_party_content_status": "Standard NHS logos excluded from OGL.",
        "redirect_notes": "No redirects.",
        "rights_source_url": "https://www.nhs.uk/about-us/terms-and-conditions/",
        "approval_rationale": "Content is hosted on the official nhs.uk domain. Covered by OGL v3.0."
    },
    {
        "source_id": "DOC-NHS-012",
        "title": "Bleeding",
        "publisher": "National Health Service (NHS)",
        "jurisdiction": "United Kingdom",
        "topic": "Bleeding",
        "document_type": "Health Information",
        "intended_audience": "General Public / Consumer",
        "language": "English",
        "canonical_url": "https://www.nhs.uk/conditions/bleeding/",
        "final_verified_url": "404 Not Found",
        "scope": "UNKNOWN",
        "approval_status": "NOT_APPROVED_FOR_THIS_CORPUS",
        "rights_status": "N/A",
        "licence_name": "N/A",
        "commercial_use_status": "PROHIBITED",
        "adaptation_status": "PROHIBITED",
        "third_party_content_status": "N/A",
        "redirect_notes": "Page returns a 404.",
        "rights_source_url": "N/A",
        "approval_rationale": "Target URL is dead."
    }
]

catalog.extend(new_docs)

with open(catalog_path, "w") as f:
    json.dump(catalog, f, indent=4)
    
print("Updated catalog successfully.")
